version: "3.8"

services:
  cassandra-1:
    image: cassandra
    container_name: cassandra-1
    restart: always
    volumes:
      - ./cassandra.cql:/cassandra.cql
      - cassandra-volume:/var/lib/cassandra
    networks:
      - cassandra-network
  cassandra-2:
    image: cassandra
    container_name: cassandra-2
    restart: always
    environment: 
      - CASSANDRA_SEEDS=cassandra-1
    networks:
      - cassandra-network
    depends_on:
      - cassandra-1
  app:
    image: node
    user: node
    container_name: app
    restart: always
    working_dir: /home/node/app
    command: 'yarn dev'
    volumes:
      - ./:/home/node/app
    ports:
      - 3000:3000
    networks:
      - cassandra-network
    depends_on: 
      - cassandra-1

networks:
  cassandra-network:

volumes:
  cassandra-volume: